### ISSUE TITLE
A sample scene with camera-facing billboards

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/MANA-community-fund-learning-content#1]
Create a sample scene for Decentraland that showcases how to use camera-facing billboards. These are entities that rotate to always show their front to the user's point of view.

Here's the Decentraland documentation for reference:  [docs.decentraland.org](https://docs.decentraland.org)
Tip: use an entity that includes the *Billboard* component.

You're free to use your creativity and imagine a scene that illustrates the objective in an interesting and engaging way. Your code must be clear and clean, as it must serve as an example for other developers trying to achieve the same kind of result.

An attached Readme.md file must list the steps required to create the project, as a lightweight tutorial.

Your content will be featured in the community section of our documentation. It may also be remixed into samples and blogposts by Decentraland.

---

创建一个示例场景，展示如何使用总是面向摄像头的平面物体，其可以旋转并根据用户位置始终正面面对用户。

以下是供参考的 Decentraland 文档： docs.decentraland.org
提示：使用包含 Billboard 组件的实体。

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。

**Comment by oscnet** [comment]
创建一个示例场景，展示如何使用总是面向摄像头的平面物体，其可以旋转并根据用户位置始终正面面对用户。

以下是供参考的 Decentraland 文档： [docs.decentraland.org](https://docs.decentraland.org)
提示：使用包含 `Billboard` 组件的实体。

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。

**Comment by leelinliew** [comment]
@oscnet Please check again if the translation for "Billboard" is correct. This might help: https://gamedev.stackexchange.com/questions/54871/what-is-billboarding-and-can-should-it-be-used-in-3d-games-to-create-special-ef
