### ISSUE TITLE
A sample scene for VR with a turn based game

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/MANA-community-fund-learning-content#2]
Create a sample scene for Decentraland that showcases how to create a turn-based game (for example a  tic-tac-toe) that supports at least two players.

Here's the Decentraland documentation for reference:  [docs.decentraland.org](https://docs.decentraland.org)
This blogpost also covers some of the challenges that creating this could involve: https://blog.decentraland.org/building-a-memory-game-using-decentralands-sdk-87ee35968f8d

You're free to use your creativity and imagine a scene that illustrates the objective in an interesting and engaging way. Your code must be clear and clean, as it must serve as an example for other developers trying to achieve the same kind of result.

An attached Readme.md file must list the steps required to create the project, as a lightweight tutorial.

Your content will be featured in the community section of our documentation. It may also be remixed into samples and blogposts by Decentraland.

---

创建 Decentraland 示例场景，展示如何创建一个至少支持两个玩家的回合制游戏(例如井字游戏)。

文档参考： docs.decentraland.org
这篇博文还涵盖了创建这个项目可能涉及的一些挑战：
https://blog.decentraland.org/building-a-memory-game-using-decentralands-sdk-87ee35968f8d

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。

ps：与此相关的 SDK 将会进行修改，请稍等。

**Comment by nearnshaw** [comment]
The SDK will undergo breaking changes soon relative to this, better wait

**Comment by oscnet** [comment]
创建 Decentraland 示例场景，展示如何创建一个至少支持两个玩家的回合制游戏(例如井字游戏)。

文档参考： [docs.decentraland.org](https://docs.decentraland.org)
这篇博文还涵盖了创建这个项目可能涉及的一些挑战：
https://blog.decentraland.org/building-a-memory-game-using-decentralands-sdk-87ee35968f8d

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。

ps：与此相关的 SDK 将会进行修改，请稍等。
