### ISSUE TITLE
Refer Hackers to SDK Hackathon

### ISSUE THREAD

**Issue by rmshea** [decentraland/MANA-community-fund-learning-content#31]
We’re organizing a private SDK hackathon, starting on June 3rd, and spanning through the 17th, with exciting prizes. 

*The Bounty*
Refer devs to the hackathon, have them submit a scene, and you'll get MANA! For every dev referral and scene submission, we will pay you 1,000 MANA. You can also participate and submit a scene to receive 1,000 MANA.

We will only consider the first 25 people that sign up (plus the other ~70 who’re already in). To register, please fill out this form: https://forms.gle/93vdQCaf5NsqJgbt9

Some more details:
- Build a Decentraland scene with the latest version of the SDK. Awards will be given to the most creative and interactive experiences. 
- Teams of up to 4 people. 
- From Jun-03 to Jun-17
- No need to own LAND or to deploy the scene to LAND to partake.
- You’ll be invited to a Slack channel, where you’ll get direct assistance from the DCL team while you work on your project.
- There will be prizes for the winning teams, adding up to 200,000 MANA:
1st prize: 100,000
2nd prize: 75,000
3rd prize: 25,000
- Districts and the DCL team will compete in separate categories for separate prizes, to keep the competition fair.

You can find information about Decentraland at https://decentraland.org/, and you can sign up below.

* SIGN UP*: https://forms.gle/93vdQCaf5NsqJgbt9

**Comment by nearnshaw** [comment]
FYI,  we've already reached our goal of 25 signups. Any new submissions won't be taken into consideration.
