### ISSUE TITLE
Create a VR scene where new entities are spawned

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/MANA-community-fund-learning-content#4]
Create a sample scene for Decentraland that showcases how multiple new entities can be created.  

- Define a type of custom entity
- Have a new entity of this type created each time something happens, which is added to the already existing ones

For example, you could have a scene where a new "bird" entity that starts flying in circles each time the user clicks a nest. 

Here's the Decentraland documentation for reference:  [docs.decentraland.org](https://docs.decentraland.org)

You're free to use your creativity and imagine a scene that illustrates the objectives in an interesting and engaging way. Your code must be clear and clean, as it must serve as an example for other developers trying to achieve the same kind of result.

An attached Readme.md file must list the steps required to create the project, as a lightweight tutorial.

Your content will be featured in the community section of our documentation. It may also be remixed into samples and blogposts by Decentraland.

---

实现如下示例场景，展示如何创建多个实体。

定义自定义实体的类型
每次当特定事件发生时，创建一个这种类型的新实体，并将其添加到现有实体中。
例如，可以设计场景：每当玩家点击鸟巢时，一只新的“鸟”（实体）就开始绕圈飞行。

文档参考： docs.decentraland.org

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。

**Comment by oscnet** [comment]
实现如下示例场景，展示如何创建多个实体。

* 定义自定义实体的类型
* 每次当特定事件发生时，创建一个这种类型的新实体，并将其添加到现有实体中。

例如，可以设计场景：每当玩家点击鸟巢时，一只新的“鸟”（实体）就开始绕圈飞行。

文档参考： [docs.decentraland.org](https://docs.decentraland.org)

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。
