### ISSUE TITLE
Create a VR scene that features user position tracking 

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/MANA-community-fund-learning-content#5]
Create a sample scene for Decentraland that showcases how things can respond to the user's position in the scene.

- Mark an area of the scene to work as a trigger in some visible way
- Create a method that is executed whenever the user enters or leaves this area

For example, you could have a scene where a trapdoor opens when the user steps on a specific tile on the ground.

Here's the Decentraland documentation for reference:  [docs.decentraland.org](https://docs.decentraland.org)

You're free to use your creativity and imagine a scene that illustrates the objectives in an interesting and engaging way. Your code must be clear and clean, as it must serve as an example for other developers trying to achieve the same kind of result.

An attached Readme.md file must list the steps required to create the project, as a lightweight tutorial.

**Comment by oscnet** [comment]
创建一个示例场景，根据用户在场景中的位置作出相应的响应。

* 以某种可见的方式标记场景的一个区域作为触发器
* 创建一个方法，该方法在用户进入或离开该区域时执行

例如，可以设计如下场景：当用户踏上地面上的一个特定的瓷砖时，一个活板门就会打开。

文档参考： [docs.decentraland.org](https://docs.decentraland.org)

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。
