### ISSUE TITLE
Create a VR scene with a simple AI character

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/MANA-community-fund-learning-content#6]
Create a sample scene for Decentraland that features a simple AI character, 

- Create a sample scene that includes a character that the user can interact with
- The character must also be able to respond to stimuli even when not directly addressed

For example, you could have a dog character that follows the user around the scene, and that occasionally moves to look around or scratch itself, independently of any input given by the user.

Here's the Decentraland documentation for reference:  [docs.decentraland.org](https://docs.decentraland.org)

You're free to use your creativity and imagine a scene that illustrates the objectives in an interesting and engaging way. Your code must be clear and clean, as it must serve as an example for other developers trying to achieve the same kind of result.

An attached Readme.md file must describe the behavior of the character.

Your content will be featured in the community section of our documentation. It may also be remixed into samples and blogposts by Decentraland.

---

创建一个示例场景，包含一个简单的 AI 角色，

创建一个可以跟用户交互的角色
在没有直接处理的情况下，这个角色也必须能够对刺激做出反应。
例如：可以场景中设计一条跟随着用户的狗，它偶尔会四处张望或搔挠一下自己，并不受用户输入的影响。

文档参考： docs.decentraland.org

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。

**Comment by oscnet** [comment]
创建一个示例场景，包含一个简单的 AI 角色，
* 创建一个可以跟用户交互的角色
* 在没有直接处理的情况下，这个角色也必须能够对刺激做出反应。

例如：可以场景中设计一条跟随着用户的狗，它偶尔会四处张望或搔挠一下自己，并不受用户输入的影响。

文档参考： [docs.decentraland.org](https://docs.decentraland.org)

您可以自由发挥你的创造力，使用有趣又吸引人的场景。代码要求清晰、干净，因为它是提供给其他想实现相同功能的开发人员的示例。

作为轻量级教程，附加的 Readme.md 文件必须写明创建项目所需的步骤。
